services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
	entrypoint: >
      /bin/sh -c "
      export DATABASE_PASS=\$$(cat /run/secrets/tm_db_password) &&
      exec /opt/app/bin/teslamate start
      "
    environment:
      - ENCRYPTION_KEY=secretkey
      - DATABASE_USER=teslamate
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - TZ=Asia/Seoul
      - VIRTUAL_HOST=localhost
      - DATABASE_POOL_SIZE=15
      - DATABASE_TIMEOUT=90000
    ports:
      - 4000:4000
    volumes:
      - ./teslamate/import:/opt/app/import
    cap_drop:
      - all
    depends_on:
      database:
        condition: service_healthy
      mosquitto:
        condition: service_started

  database:
    image: postgres:17-trixie
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB_FILE=teslamate
      - TZ=Asia/Seoul
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U teslamate -d teslamate"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - GF_DATABASE_PASSWORD_PATH=/run/secrets/db_password
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - TZ=Asia/Seoul 
    ports:
      - 3001:3000
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      database:
        condition: service_healthy

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    environment:
      - TZ=Asia/Seoul
    ports:
      - 1884:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log


secrets:
  db_password:
    file: /dev/shm/.tmp_postgres_pw
